### PR TITLE
Fixed configuration bug. Added json support

### PR DESCRIPTION
**Pull request by Littlejd1997**

### CODE REVIEW

**Comment by atyndall** [comment]
Hi @Littlejd1997, thanks for your contribution.
Could you provide a code example of the bug your PR aims to fix?
And with your new JSON feature, could you explain the rationale behind the feature, and how your changes enable that feature?

**Comment by Littlejd1997** [comment]
An error would occur if no explicit configuration was used.

The second json feature was for encrypting fields which were formerly jsonb columns in a postgres db. Basically, if a hash is passed in, then its converted to json and then encrypted and stored. Likewise, if it can parse json, it will parse it and return a hash on decryption

**Comment by Littlejd1997** [comment]
Also, I was getting a "must exist to store encrypted data" error when running some of our older migrations before the enc field was created and our migrations would fail

**Comment by atyndall** [comment]
With your JSON feature, if you enable Data Serialization ([described here](https://github.com/appbot/kms_rails/blob/master/README.md#data-serialization)) then high level data structures should already be encoding and decoded transparently by the msgpack library. Does your proposed feature differ in function from this?

With your "must exist to store encrypted data" error, I can see why that might occur, it might make more sense to not just comment it out, but move the validation to inside the `define_method "#{field}="` and `define_method "#{field}"` methods.

**Comment by atyndall** [comment]
Thanks, I'll have a look into it Monday. Do you have a reply to my questions above?

**Comment by atyndall** [comment]
I've addressed the bugs you've reported, please let me know about that JSON issue if it continues to be one.

**Pull request closed without merging**
